// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ccwdwmbvzwqmazhzjfoq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNjd2R3bWJ2endxbWF6aHpqZm9xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzNTQzMjksImV4cCI6MjA2NzkzMDMyOX0._ch-0tbPai5RT1a8qHaJt1XnVeuIOBoIDlOYF2kz_bg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});